// Browser client only. App IDs are public; no developer credential belongs here.
const enc=new TextEncoder(),dec=new TextDecoder();
const b64=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const un64=text=>{if(typeof text!=='string'||!/^[\w-]+$/.test(text))throw new Error('Invalid recovery file');const bytes=Uint8Array.from(atob(text.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));if(b64(bytes)!==text)throw new Error('Invalid recovery file');return bytes;};
const random=()=>b64(crypto.getRandomValues(new Uint8Array(32)));
const digest=async text=>b64(await crypto.subtle.digest('SHA-256',enc.encode(text)));
export function createAuthClient({appId,redirectUri,endpoint='https://api.vibecodestorage.com/auth',sessionStore=globalThis.sessionStorage,keyStore=globalThis.localStorage}={}){
 const url=new URL(endpoint);if(url.protocol!=='https:'&&url.hostname!=='localhost')throw new Error('Auth requires HTTPS');endpoint=endpoint.replace(/\/$/,'');
 if(typeof appId!=='string'||!/^[\w-]{24}$/.test(appId))throw new Error('Use the public app ID from registration');
 const prefix='vcs-auth:'+endpoint+':'+appId;
 let token=sessionStore?.getItem(prefix)||null,identity=null,material=null;
 const context=()=>JSON.stringify(['vcs-private-v1',endpoint,appId,identity.userId]);
 const localKey=()=>prefix+':data:'+identity.userId;
 async function call(path,method='GET',body){const r=await fetch(endpoint+path,{method,credentials:'omit',headers:{'X-VCS-App':appId,...(token?{Authorization:'Bearer '+token}:{}),...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});let data;try{data=await r.json();}catch{throw new Error('Storage returned an unexpected response');}if(!r.ok)throw Object.assign(new Error(typeof data.error==='string'?data.error:data.error?.message||'Storage request failed'),{status:r.status,retryAfter:r.headers.get('Retry-After')});return data;}
 const requireIdentity=()=>{if(!identity)throw new Error('Sign in first');};
 const requireKey=()=>{requireIdentity();if(identity.mode==='customer-private'&&!material)throw new Error('Unlock your data with its recovery file or an existing device');};
 async function derive(raw){const source=await crypto.subtle.importKey('raw',raw,'HKDF',false,['deriveKey']),params=label=>({name:'HKDF',hash:'SHA-256',salt:enc.encode(context()),info:enc.encode(label)});return {aes:await crypto.subtle.deriveKey(params('records'),source,{name:'AES-GCM',length:256},false,['encrypt','decrypt']),mac:await crypto.subtle.deriveKey(params('names'),source,{name:'HMAC',hash:'SHA-256',length:256},false,['sign'])};}
 async function recordId(key){if(typeof key!=='string'||!key||key.length>128)throw new Error('Record name must contain 1–128 characters');requireKey();return identity.mode==='app-managed'?key:b64(await crypto.subtle.sign('HMAC',material.mac,enc.encode(key)));}
 async function encrypt(id,key,value){const nonce=crypto.getRandomValues(new Uint8Array(12));return {v:1,alg:'A256GCM',nonce:b64(nonce),ciphertext:b64(await crypto.subtle.encrypt({name:'AES-GCM',iv:nonce,additionalData:enc.encode(context()+':'+id)},material.aes,enc.encode(JSON.stringify({key,value}))))};}
 async function decrypt(row){if(identity.mode==='app-managed')return row;const e=row.value;const plain=JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(e.nonce),additionalData:enc.encode(context()+':'+row.key)},material.aes,un64(e.ciphertext))));if(await recordId(plain.key)!==row.key)throw new Error('Encrypted record identity did not match');return {key:plain.key,value:plain.value,version:row.version};}
 async function unlock(recovery,{remember=true}={}){requireIdentity();if(identity.mode!=='customer-private')throw new Error('This app manages data keys for you');if(recovery?.format!=='vcs-customer-key-v1'||recovery.appId!==appId||recovery.userId!==identity.userId||recovery.endpoint!==endpoint)throw new Error('Recovery file belongs to another account or app');const raw=un64(recovery.key);if(raw.length!==32)throw new Error('Invalid data key');const commitment=await digest(context()+':'+recovery.key);let vault;try{vault=await call('/api/vault');}catch(e){if(e.status!==404)throw e;vault=await call('/api/vault','PUT',{commitment});}if(vault.commitment!==commitment)throw new Error('Recovery file does not unlock this account');material=await derive(raw);if(remember)keyStore?.setItem(localKey(),JSON.stringify(recovery));return {unlocked:true};}
 async function resume(){identity=await call('/api/me');material=null;if(identity.mode==='customer-private'){const saved=keyStore?.getItem(localKey());if(saved){try{await unlock(JSON.parse(saved),{remember:false});}catch{/* Keep identity signed in, but locked; never generate a replacement key. */}}}return {...identity,locked:identity.mode==='customer-private'&&!material};}
 return {
  async signIn({resetToken}={}){const verifier=random(),state=random();sessionStore.setItem(prefix+':flow',JSON.stringify({verifier,state}));const target=new URL(endpoint+'/authorize');target.search=new URLSearchParams({client_id:appId,redirect_uri:redirectUri,code_challenge:await digest(verifier),code_challenge_method:'S256',state});if(resetToken!==undefined){if(!/^[\w-]{43}$/.test(resetToken))throw new Error('Invalid reset link');target.hash='vcs-reset='+resetToken;}globalThis.location.assign(target);},
  async finishSignIn(callbackUrl=globalThis.location.href){const u=new URL(callbackUrl),expected=new URL(redirectUri);if(u.origin!==expected.origin||u.pathname!==expected.pathname)throw new Error('Wrong sign-in callback');const saved=sessionStore.getItem(prefix+':flow');sessionStore.removeItem(prefix+':flow');const flow=saved&&JSON.parse(saved);if(!flow||u.searchParams.get('state')!==flow.state)throw new Error('Sign-in state did not match; start again');globalThis.history?.replaceState(null,'',expected.pathname);const result=await call('/token','POST',{client_id:appId,redirect_uri:redirectUri,code:u.searchParams.get('code'),code_verifier:flow.verifier});token=result.access_token;sessionStore.setItem(prefix,token);return resume();},
  resume,unlock,
  async prepareRecovery(){requireIdentity();if(identity.mode!=='customer-private')throw new Error('This app does not need a data recovery file');try{await call('/api/vault');throw new Error('A vault already exists; use its existing recovery file or device');}catch(e){if(e.status!==404)throw e;}return {format:'vcs-customer-key-v1',endpoint,appId,userId:identity.userId,key:random()};},
  exportRecovery(){requireKey();const saved=keyStore?.getItem(localKey());if(!saved)throw new Error('Use your existing recovery file');return JSON.parse(saved);},
  async getEntry(key){const id=await recordId(key);return decrypt(await call('/api/records/'+encodeURIComponent(id)));},
  async get(key){return (await this.getEntry(key)).value;},
  async list(){requireKey();const rows=(await call('/api/records')).records;return Promise.all(rows.map(decrypt));},
  async set(key,value,{version}={}){const id=await recordId(key);if(!Number.isSafeInteger(version)||version<0)throw new Error('Supply version 0 to create or the current version to update');return call('/api/records/'+encodeURIComponent(id),'PUT',{value:identity.mode==='customer-private'?await encrypt(id,key,value):value,version});},
  async delete(key,{version}={}){const id=await recordId(key);return call('/api/records/'+encodeURIComponent(id),'DELETE',{version});},
  async signOut({forgetDevice=false}={}){if(forgetDevice&&identity)keyStore?.removeItem(localKey());try{if(token)await call('/api/logout','POST',{});}finally{token=null;identity=null;material=null;sessionStore?.removeItem(prefix);}},
  get signedIn(){return !!identity;},get locked(){return !identity||(identity.mode==='customer-private'&&!material);},get mode(){return identity?.mode;}
 };
}
